Build and install scripts/sign-file
akmods always tries to sign built modules with locally generated key.

Fixes following error:

	2026/09/01 22:09:43 akmods: Building RPM using the command '/usr/sbin/akmodsbuild --kernels 6.18.42-3.rpi5.fc44.aarch64 /usr/src/akmods/aic8800d80-kmod.latest'
	+ /usr/lib/rpm/brp-compress
	+ /usr/lib/rpm/brp-strip /usr/bin/strip
	+ /usr/lib/rpm/brp-strip-comment-note /usr/bin/strip /usr/bin/objdump
	+ /usr/lib/rpm/redhat/brp-strip-lto /usr/bin/strip
	+ /usr/lib/rpm/check-rpaths
	+ /usr/lib/rpm/redhat/brp-mangle-shebangs
	+ /usr/lib/rpm/brp-remove-la-files
	+ /usr/lib/rpm/redhat/brp-python-rpm-in-distinfo
	+ env /usr/lib/rpm/redhat/brp-python-bytecompile '' 1 0 -j4
	+ /usr/lib/rpm/redhat/brp-python-hardlink
	+ /usr/bin/add-det --brp -j4 /tmp/akmodsbuild.hRQrj76e/BUILD/aic8800d80-kmod-0.20260824git2895da2-build/BUILDROOT
	Handler jar skipped: jar handler requires $SOURCE_DATE_EPOCH to be set
	Handler gzip skipped: gzip handler requires $SOURCE_DATE_EPOCH to be set
	Handler zip skipped: zip handler requires $SOURCE_DATE_EPOCH to be set
	Scanned 20 directories and 94 files,
		processed 0 inodes,
		0 modified (0 replaced + 0 rewritten),
		0 unsupported format, 0 errors
	+ /usr/bin/linkdupes --brp /tmp/akmodsbuild.hRQrj76e/BUILD/aic8800d80-kmod-0.20260824git2895da2-build/BUILDROOT/usr
	Scanned 14 directories and 91 files,
		considered 91 files, read 0 files, linked 0 files, 0 errors
		sum of sizes of linked files: 0 bytes
	+ '[' 1 -eq 1 ']'
	+ '[' -x /usr/lib/rpm/brp-kmodsign ']'
	+ '[' -e /etc/pki/akmods/private/private_key.priv ']'
	+ '[' -e /etc/pki/akmods/certs/public_key.der ']'
	+ /usr/lib/rpm/brp-kmodsign /etc/pki/akmods/private/private_key.priv /etc/pki/akmods/certs/public_key.der /tmp/akmodsbuild.hRQrj76e/BUILD/aic8800d80-kmod-0.20260824git2895da2-build/BUILDROOT/lib/modules/6.18.42-3.rpi5.fc44.aarch64/extra/aic8800d80/ /usr/src/kernels/6.18.42-3.rpi5.fc44.aarch64
	brp-kmodsign: /usr/src/kernels/6.18.42-3.rpi5.fc44.aarch64/scripts/sign-file not found or not executable
	error: Bad exit status from /var/tmp/rpm-tmp.8Zgpi4 (%install)

	RPM build warnings:
		%source_date_epoch_from_changelog is set, but %changelog has no entries to take a date from

	RPM build errors:
		Bad exit status from /var/tmp/rpm-tmp.8Zgpi4 (%install)

(cherry picked from commit 3412ff53c19d538aaa228c416e5419e11ef46a49)